api:
  twitter_bearer_token: "your_info_here"
  arcgis_username: "your_info_here"
  arcgis_password: "your_info_here"

data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"

models:
  spacy_model: "en_core_web_lg"